In [12]:
from cobra.io import load_model
model = load_model('textbook')
model

In [13]:
solution = model.optimize()
solution

In [14]:
model.summary()

In [15]:
model.metabolites.nadh_c.summary()